### ISSUE TITLE
Javascript client impl

### ISSUE THREAD

**Issue by simon-jentzsch** [raiden-network/microraiden#107]
I don't think we are the only ones, that would like to integrate a microraiden-client into our ios/android-app (which uses react-native), we cannot use the python-code. 
Are there any plans or can we help to implement the javascript version?

**Comment by pcppcp** [comment]
Hi Simon,
there's a [javascript client](https://github.com/raiden-network/microraiden/blob/master/microraiden/microraiden/webui/js/microraiden.js) that we currently use for browser webui - however it doesn't depend on anything else but `web3` compatible lib (in browser that is Metamask and Parity, unfortunately I don't know what is available android/iOS). Maybe take a look at it first, it implements all the functionality required.

**Comment by andrevmatos** [comment]
Hi, Simon.
Thanks for your interest in µRaiden. We have [JS ES6 libraries](https://github.com/raiden-network/microraiden/blob/master/microraiden/microraiden/webui/js/microraiden.js), [example code](https://github.com/raiden-network/microraiden/blob/master/microraiden/microraiden/webui/js/main.js) and [documentation](https://github.com/raiden-network/microraiden/tree/master/microraiden/microraiden/webui). It should be both browser and Node.js compatible. The code should be pretty straightforward to read, but you're free to ask any question in the [Raiden's Gitter](https://gitter.im/raiden-network/raiden) while we don't have an official support channel yet.
