### ISSUE TITLE
Display an error if tx expires

### ISSUE THREAD

**Issue by pcppcp** [raiden-network/microraiden#109]
When testing on Ropsten, tx confirmation takes quite a long time and sometimes it is not included within the default 14-blocks wait period. In that case, webui should display an error message.

It would be also useful to display the countdown somehow to give user a feedback that something is actually happening.
Simplest solution would be to update the text displayed, i.e. "Waiting for confirmation (4/15)"

**Comment by pcppcp** [comment]
Here's a screenshot:
http://i.imgur.com/TPSdDA1.png

**Comment by andrevmatos** [comment]
#106 also fixes this issue , as it didn't show the error dialog only because of a small typo in a code that were also changed by that PR, so I fixed it there too.
