### ISSUE TITLE
Transactions do not propagate using MetaMask Ropsten backend

### ISSUE THREAD

**Issue by pcppcp** [raiden-network/microraiden#115]
Observed while testing Ropsten deployment: when using Metamask, transactions are confirmed after a long time or do not get confirmed at all. (webui's default confirmation window of 15 blocks expires)

With local geth node transaction is confirmed after 3-6 blocks.

**Comment by andrevmatos** [comment]
I've increased the wait time to `30` in #106 , but still not sure how to handle that properly.

**Comment by pcppcp** [comment]
I think a simple error message after expiration would be sufficient.
This will be easily solved once the client can sync its state via the REST api.

**Comment by pcppcp** [comment]
probably related to gas price
