### ISSUE TITLE
proxy-tutorial.md is not correct

### ISSUE THREAD

**Issue by makemesteaks** [raiden-network/microraiden#119]
Hello,

According to examples/echo_server.py I need to pass

`channel_manager_address, private_key, state_file`

to microraiden/proxy/paywalled_proxy.py but the constructor is not expecting it:

```
    def __init__(self,
                 channel_manager,
                 flask_app=None,
                 paywall_html_dir=None,
                 paywall_js_dir=None):
```

giving an exception on the first assert (as well as the next ones).

```
     if not flask_app: 
            self.app = Flask(__name__, static_url_path='/mystatic')
        else:
            assert isinstance(flask_app, Flask)
            self.app = flask_app
```

Am I doing something wrong or is this the expected behaviour? 

Thank you

**Comment by jannikluhn** [comment]
> Am I doing something wrong or is this the expected behaviour?

Neither, it's a bug. I've fixed it in this PR  #120. Thank you for reporting it!
