### ISSUE TITLE
Cannot use wikipaydia with private chain

### ISSUE THREAD

**Issue by pydo** [raiden-network/microraiden#121]
**Description**
I'm trying to use the demo wikipaydia demo app with a private ethereum chain. I bootstrapped a few nodes using this project https://github.com/dstarcev/parity-poa-playground. I didn't setup the token contract on my private chain, but I don't know why that would prevent the web service from finding my unlocked ethereum accounts.

**Procedure**
1. Start parity node listening with RPC port on 8545
2. Unlock an account `curl --data '{"method":"personal_unlockAccount","params":["0x00bd138abd70e2f00903268f3db08f2d25677c9e","node0",null],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST localhost:8545`
2. Start microraiden flask application server:
` (env) user@user-super:~/coding/microraiden/microraiden$ python -m microraiden.examples.wikipaydia  --private-key=key.json start`
3. Open http://localhost:5000/wiki/doggo.jpg in browser

**Expected behavior**
Payment window can find the one account I unlocked

**Actual behavior**
Payment window displays
` No accounts found!
You may need to unlock your account on your Web3 provider (Metamask/Mist/Parity)`

**Additional info**
My browser is polling `http://localhost:8545/` with an OPTIONS call every second. Parity responds with a 200 so I know that both services can communicate with each other.

**Comment by andrevmatos** [comment]
Hi, @pydo . The paywall page is actually a dApp which talks with your web3-enabled browser. For that, you don't need to unlock your account in Parity with RPC. Just installs parity's browser extension, and it should be used by the paywall to request the needed transactions. It should be offered to you in the first time you access parity's web interface with your browser. If you're running parity inside a docker, you may need to enable CORS and allow external connection (e.g. through `--unsafe-expose` option). Please, follow parity's documentation on how to set up it.

**Comment by andrevmatos** [comment]
Closing as no new reply on that. Please, reopen if you followed documentation and still couldn't make it work.
