### ISSUE TITLE
ChannelManagerState.store uses shutil.copy2 instead of atomic rename

### ISSUE THREAD

**Issue by nkonovalov** [raiden-network/microraiden#124]
the store method should use os.rename instead of shutil.copy2.

The call to flush does not make sense without calling os.fsync. It will be flushed anyway when closing the the file (the with block does that).

see https://docs.python.org/3/library/os.html#os.fsync

**Comment by nkonovalov** [comment]
I see now that the load method tries to detect an empty state file and loads from the temp file.
I fail to see the point of that. Can you please explain what's the purpose?

**Comment by andrevmatos** [comment]
Will superseded by #129 , no need to copy/move database.

**Comment by loredanacirstea** [comment]
@pcppcp , we can close this, right?

**Comment by pcppcp** [comment]
Fixed by PR 129
