### ISSUE TITLE
filename should not be part of ChannelManagerState

### ISSUE THREAD

**Issue by nkonovalov** [raiden-network/microraiden#126]
I can't move the state file otherwise to a different path.

**Comment by loredanacirstea** [comment]
Fixed in https://github.com/raiden-network/microraiden/pull/145

**Comment by pcppcp** [comment]
btw, channel manager still references the state file.

See 
`channel_manager.py:295-296` (this raises an exception when starting uRaiden on demo site w/o synced chain)
https://github.com/jannikluhn/microraiden/blob/5f69f69a7be82dc9ee87b2c7f1d788ba65b23260/microraiden/microraiden/channel_manager.py#L295
and 
`channel_manager.py:257`
https://github.com/jannikluhn/microraiden/blob/5f69f69a7be82dc9ee87b2c7f1d788ba65b23260/microraiden/microraiden/channel_manager.py#L257 
 (there should be key check before calling `pop()`)

**Comment by pcppcp** [comment]
Fixed in PR #180
