### ISSUE TITLE
Custom Client should be able to receive contract configs from server (http headers + api)

### ISSUE THREAD

**Issue by loredanacirstea** [raiden-network/microraiden#131]
REST endpoint for:
- [x] channel manager contract address
- [x] token contract address
- [x] receiver address
- [x] channel manager contract ABI
- [x] token contract ABI

For custom client implementations

(now we have to places with the contract ABIs, would be nice to have an endpoint for that. we can also consider etherscan api for getting the abi - but an external dependency wouldn't be nice though)

**Comment by pcppcp** [comment]
addresses will be available via `/stats/` endpoint. For abis, I'll add `/manager_abi` and `/token_abi`
