### ISSUE TITLE
Review docs and update

### ISSUE THREAD

**Issue by loredanacirstea** [raiden-network/microraiden#138]
Known issues

- [x] update contract deployment, testing commands

- [x] document populus.json chain configs - let them know they can change timeout & ips

- [x] document proxy examples parameters

- [x] review and update proxy tutorial

- [x] how to integrate custom deployed contracts

- [x] document config.py

- [x] proxy command line arguments documented

- [x] review & update contract docs, put addresses for main net & test nets

- [x] contract disclaimer

- [x] update WebUI docs

**Comment by ianseyer** [comment]
Please include failure cases/fault tolerance schemes! (receiving node offline, contestation trees, etc)

**Comment by loredanacirstea** [comment]
Proxy tutorial updated: https://github.com/raiden-network/microraiden/pull/225
Quick setup: https://github.com/raiden-network/microraiden/pull/226
Contract testnet deployment script fix: https://github.com/raiden-network/microraiden/pull/229
https://github.com/raiden-network/microraiden/pull/230
