### ISSUE TITLE
 Improve smart contract gas cost for verifying balance proofs.

### ISSUE THREAD

**Issue by loredanacirstea** [raiden-network/microraiden#140]
Populus gas estimation (might be higher in real life):

test_close_by_receiver 104740
test_close_by_sender 160707 (cooperative close)
test_close_by_sender_challenge_settle_by_receiver 196961
test_close_by_sender_challenge_settle_by_sender 147925

**Comment by andrevmatos** [comment]
Current gas usage for cooperative close: 312k
![image](https://user-images.githubusercontent.com/587021/32756737-b9712450-c8c2-11e7-9ece-b0431ade6e05.png)

**Comment by loredanacirstea** [comment]
web3.js estimates gas poorly for this one. I closed a channel with cooperative close with 212k gas. It could be even less, though it fails with 190k gas. Will be solved by https://github.com/raiden-network/microraiden/pull/176

https://kovan.etherscan.io/tx/0x69179d2cf94c05d2860af9982077ae011c6506438fc728aab5e76fd11a6eae35

**Comment by andrevmatos** [comment]
I don't think it's only an estimation error, but I can't see why my account is giving so different results:
https://kovan.etherscan.io/tx/0x1e3f89419f9f21eb59e7b27bfdb3f4ac0232ebfcacf0c761e54aa39246f3ea4d

**Comment by loredanacirstea** [comment]
Both transactions show `Gas Used By Txn: 193057`.
With MetaMask, I manually set the gas - the original estimation was the same (312k)
