### ISSUE TITLE
REST endpoint - microtransfer

### ISSUE THREAD

**Issue by loredanacirstea** [raiden-network/microraiden#142]
endpoint for doing micropayments from remote clients. This is what I used in the `robo-demo` branch for devcon3. Client was served by node-red.

In https://github.com/raiden-network/microraiden/blob/master/microraiden/microraiden/proxy/resources/management.py
Along the lines of:

```
def post(self, sender_address, opening_block, balance):
        parser = reqparse.RequestParser()
        parser.add_argument('signature', type=str)
        args = parser.parse_args()
        if args['signature'] is None:
            return "Bad signature format", 400
        try:
            (sender, received) = self.channel_manager.register_payment(
                sender_address,
                opening_block,
                balance,
                args['signature']
            )
```

**Comment by pcppcp** [comment]
So if I understand it correctly it's basically a REST endpoint you can send payment to? 
What's a use case for this if there's no action attached to the payment?

**Comment by loredanacirstea** [comment]
The payment is the action. 
It frees the client from the cookies used to communicate with the proxy. You can develop the client separately. 
Use case demonstrated with the node-red, robo demo. Implementing that with cookies would have been impossible, because it's not a paywall use case. It's an m2m one.

I personally think this adds a lot more freedom to develop apps - that's why I was pushing for it. + not hard to implement. + raiden also has APIs.

I actually think providing both cookies + 402 http header AND apis would be optimal - for a future release.

**Comment by andrevmatos** [comment]
Cookies <-> Headers are compatible, and they should attend the needs for web clients and m2m clients. The idea is that it's a kind of _metadata_ attached to communication/actions which are then transparently performed through traditional API requests. Of course, we could make these "metadata" explicit by offering the possibility of them being incorporated in the body, together with arbitrary "data", although the idea of a successful payment => valid/verifiable reply gets a little bit blurry.

**Comment by loredanacirstea** [comment]
I am closing this issue. Using `Expensive` to define payable endpoints is more than enough with static & dynamic pricing. Not sure if this was not implemented back then or I just had issues setting it up.
