### ISSUE TITLE
examples demo_proxy fails

### ISSUE THREAD

**Issue by pawanjay176** [raiden-network/microraiden#146]
I am trying to run the demo_proxy example from the README
I am using an infura node as my ethereum rpc provider. 

However, I keep geting
`web3.exceptions.BadFunctionCallOutput: Could not transact with/call contract function, is contract deployed correctly and chain synced?

What am I doing wrong?
`

**Comment by freehere107** [comment]
How do you solve this mistake?

**Comment by pawanjay176** [comment]
I was running a ropsten node but the contract is actually deployed on the kovan network!
Switched to kovan network and it worked perfectly!

**Comment by freehere107** [comment]
It's ok, great, but how my address join this contract channel ?
