### ISSUE TITLE
Kovan contract open channel error 

### ISSUE THREAD

**Issue by freehere107** [raiden-network/microraiden#148]
I has Token deposit to open a channel , tx has comfirm ,but my address 'No channel was found registered for this account on this website'

**Comment by andrevmatos** [comment]
Please, paste browser's console output on this session, and any different server log lines you may find. Just tested here with a clean setup, parity over Kovan, and it's working.

**Comment by freehere107** [comment]
Sorry
1. When i access http://localhost:5000/teapot.jpg，  web page print yellow warnning 

>  No channel was found registered for this account on this website.

and  write loading
>  In order to proceed...

no web console found in this page ,only css/js loadding log

2. Ok,I will open channel .Click deposit button and then display bule loading ``The transactions are being processed.Please authorize with your Ethereum client.``  and my MateMask has a transaction i will submit.Waiting the transaction pennding.

server console 
```
DEBUG:blockchain:received unconfirmed ChannelOpened event (sender 0x00a1537d251a6a4c4effab76948899061fea47b9, block number 4723791) 
INFO:channel_manager:unconfirmed channel event received (sender 0x00a1537d251a6a4c4effab76948899061fea47b9, block_number 4723791) 
DEBUG:blockchain:filtering for events u:4723792-4723792 c:4723791-4723791 @4723792 
DEBUG:blockchain:received ChannelOpened event (sender 0x00a1537d251a6a4c4effab76948899061fea47b9, block number 4723791) 
INFO:channel_manager:new channel opened (sender 0x00a1537d251a6a4c4effab76948899061fea47b9, block number 4723791) 

```
web console 
```
microraiden.js:266 Token balance 0x04c7f744a0c751d89e99ae79a39060ec6f3c4397 e {s: 1, e: 2, c: Array(1)}
microraiden.js:275 transferTxHash 0x78beb49fabd6266f911d34ec7ebe0e749052adcabe46e17c68f23772aecaf809
```

but web page Nothing happened and still ``The transactions are being processed.Please authorize with your Ethereum client.``

**Comment by freehere107** [comment]
ok，lastest version bug fixed
