### ISSUE TITLE
pad_left not defined

### ISSUE THREAD

**Issue by ianseyer** [raiden-network/microraiden#165]
Attempted to deploy contract to testnet with a known token-address by executing:

`python -m deploy.deploy_testnet --owner <my wallet> --chain ropsten --token-address <contract address>`

However, this returns: `NameError: name 'pad_left' is not defined`

In addition, removing the pad_left() call yields: `NameError: name 'remove_0x_prefix' is not defined`

Removing the `0x` from the token-address flag yields an ABI error.

**Comment by loredanacirstea** [comment]
@ianseyer , are you using the last `master` version of the code? 
`pad_left` & `remove_0x_prefix` should be imported correctly https://github.com/raiden-network/microraiden/blob/master/contracts/deploy/deploy_testnet.py#L8

**Comment by pcppcp** [comment]
@ianseyer can you post output of `pip freeze | grep eth`?
Maybe some of the ethereum libs' API has changed.

**Comment by pcppcp** [comment]
No reply for 14 days -  please reopen if you still need help.
