### ISSUE TITLE
Support other HTTP methods than GET

### ISSUE THREAD

**Issue by devium** [raiden-network/microraiden#187]
Currently, µRaiden only supports `GET` requests to be performed by the client and forwarded by the server. When using REST APIs, however, you usually need more than that.

While other methods could be enclosed in the `GET` request body, the Python client currently has no easy way to include that body in the request, other than overriding the `_request_resource()` method.

It would be nice if either
* (easy, short term) The client would support arbitrary request bodies or
* (more complex, long term) Both client and server learn to natively handle and forward POST/PUT/PATCH/etc.

**Comment by konradkonrad** [comment]
I think it would be really awesome, if
- the client could just expose a patched `requests` module (and support `microraiden_requests.get`, `microraiden_requests.post`, ... ). Ideally, that would allow developers to swap out `requests` from an off-the-shelf library and immediately speak microraiden...
- the server could just wrap any `flask` (or WSGI?) app.

For starters, a patched `requests.request(method, url, **kwargs)` could get us pretty far for the client.

**Comment by pcppcp** [comment]
Fixed in #272 #258
