### ISSUE TITLE
Update web3.py (and pyethereum)

### ISSUE THREAD

**Issue by devium** [raiden-network/microraiden#212]
Known issues:
* We're using quite some internal code from `web3.py` and `pyethereum`, especially for handling logs and sending pre-signed transactions.
* Some of these internal code calls make us stuck at version `web3-3.11.1` and `pyethereum < 2.0.0`. Especially using µRaiden in external projects makes us lose out on quite some new features already.

On the same note of package dependencies, we should probably also try and get rid of pyethereum since according to @LefterisJP this will be deprecated sooner or later. We should be able to replace its tester chain with `web3`'s tester.

**Comment by devium** [comment]
Just a quick overview over the dependencies messing things up here:

* `web3.py` (even in its newest version) does not support offline signing of transaction, so we need to create and sign these transactions using `pyethereum` ourselves, then send them via `eth_sendRawTransaction`
* `web3.py` requires `pyethereum < 2.0.0`, so we cannot sign transactions using `pyethereum` without losing support for [EIP155](https://github.com/ethereum/eips/issues/155) replay protection
* For these reasons, we're currently implementing EIP155-style signing ourselves which is not a good long-term solution, especially since we're stuck on outdated libraries.

Currently, I am not aware of any libraries that offer the complete package we need here. Maybe `pyEVM` will save us one day. Until then I think we're stuck with the current dependency issue.

**Comment by andrevmatos** [comment]
Done in #327
