### ISSUE TITLE
Make server responses and status codes available in the client

### ISSUE THREAD

**Issue by devium** [raiden-network/microraiden#249]
Several possible ways to do this:
* Return the last (arguably most important) status code, header, and response body from the `run()` method
* Return a list of all status codes, headers, and response bodies involved in a single `run()` call from the `run()` method
* Introduce an `on_response()` callback that also returns a `bool` indicating a retry.

I slightly prefer the last option.

**Comment by pcppcp** [comment]
`on_response()` can work. It's in line with current design of the client and I like that user can customize behavior on failure.
