### ISSUE TITLE
Channel Closing Incentives

### ISSUE THREAD

**Issue by heikoheiko** [raiden-network/microraiden#3]
Opening a channel costs gas. This is always payed by the `sender`.
Closing a channel also costs gas. Let's look at the incentives to cooperate. 

## Receiver wants to settle
Reasons of doing so would be, 
- channel ran out of funds and the sender is not expected to top-up, i.e. sender is not expected to  pay for the closing cost
- sender became inactive, receiver wants to settle

Receiver can always settle a channel with a single transaction. 

## Sender wants to settle
If he has agreed with the receiver on closing the channel and received a sender signed proof of agreement on the last balance, then the sender can settle the channel with a single transaction. 

### Receiver perspective
If the sender does not cooperate, the client can close with a wrong balance which the receiver needs to challenge. In order to not having to pay for a tx, the receiver is incentivised to cooperate when the client requests an agreement on closing the channel. 

### Sender perspective
Requesting closing of a channel is more expensive (additional storage allocated) than then directly settling it. Also the party settling the channel will get a gas refund from the freeing the storage. Also settlement is not deferred by a challenging period. Therefore the client will try to settle the channel with one transaction based on a signed closing agreement from the receiver.

**Comment by devium** [comment]
This works currently:
* Receiver can always close the channel immediately.
* Sender can perform a cooperative close by requesting a signed balance proof ("closing signature") from the receiver.
