### ISSUE TITLE
depend on eth-tester and not ethereum-tester

### ISSUE THREAD

**Issue by gleim** [raiden-network/microraiden#303]
ethereum-tester is an out of date dependency and breaks new builds pulling in microraiden

**Comment by pcppcp** [comment]
We've now freezed `ethereum-tester` to version `0.4.0`. The reason is an incompatible `web3` which in new version removed some of the function we use in raiden and we need to replace them.

**Comment by pcppcp** [comment]
Fixed by PR #327
