### ISSUE TITLE
JS client needs the contract creation block for efficiently getting past events

### ISSUE THREAD

**Issue by loredanacirstea** [raiden-network/microraiden#349]
Issue: MetaMask has become unreliable when retrieving past events using `fromBlock = 0`. There is no web3.js API to get the contract creation block number/transaction hash from the contract address.

There were several proposed solution in our discussions, documented here:
- :+1: → adding a public contract variable on contract creation storing the block number
- :smile: → adding a [config.py](github.com/raiden-network/microraiden/blob/master/microraiden/microraiden/config.py) variable , available through the `/stats` endpoint
- :heart: → use the block number of a first open channel as a value passed to the webui via `/stats` endpoint

**Comment by loredanacirstea** [comment]
We have settled on "adding a `config.py` variable , available through the `/stats` endpoint" at this time.

**Comment by pcppcp** [comment]
Fixed in PR #362
