### ISSUE TITLE
JS Server?

### ISSUE THREAD

**Issue by emschwartz** [raiden-network/microraiden#365]
Are there any plans to implement the server functionality in the JavaScript library?

Thanks!

**Comment by andrevmatos** [comment]
Hi, @emschwartz .
There's no plan to date to provide a JS/node implementation of the µRaiden server/service/libraries, but it should not be hard. The documentation is pretty extensive, and the examples and tests covers all the details we could imagine. We're open to PRs implementing it, and available to help anyone or any company willing to contribute man power to this effort.
