### ISSUE TITLE
Do not compare maintenance version of the package.

### ISSUE THREAD

**Issue by pcppcp** [raiden-network/microraiden#367]
### Problem
We now have two places where versions are stored - in the contract source file (effectively it is `microraiden/data/contract.json`) and in `microraiden/config.py`.
To prevent users from accidentally using older uRaiden python code with a different version of the deployed contract, we do a version check on the startup.

Currently it looks like this - a simple string comparison
```python
    def check_contract_version(self):
        deployed_contract_version = self.channel_manager_contract.call().version()
        if deployed_contract_version != CHANNEL_MANAGER_CONTRACT_VERSION:
            raise InvalidContractVersion("Incompatible contract version: expected=%s deployed=%s" %
                                         (CHANNEL_MANAGER_CONTRACT_VERSION,
                                          deployed_contract_version))
```

So far it has worked as expected - until I tried to update microraiden pypi package. Pypi forces maintainters to bump the version every time the package gets an update.

### Solution

As we use major-minor-maintenance version schema, I suggest to check major and minor version only for the contract version check. The code may require maintenance updates on pypi from time to time and provided we don't break contract API compatibility excluding the maintenance version number from the check will not be an issue.

**Comment by loredanacirstea** [comment]
I agree with just comparing the major and minor versions of the contract and pypi package.
