### ISSUE TITLE
not check withdraw_balances le _balance in settleChannel.

### ISSUE THREAD

**Issue by nakajo2011** [raiden-network/microraiden#392]
in withdraw: check withdraw_balances[key] less than _balance
https://github.com/raiden-network/microraiden/blob/01346c05ac42abb9e4534888a64e0ca82d7fe448/contracts/contracts/RaidenMicroTransferChannels.sol#L302

but, in settleChannel: not check.
https://github.com/raiden-network/microraiden/blob/01346c05ac42abb9e4534888a64e0ca82d7fe448/contracts/contracts/RaidenMicroTransferChannels.sol#L631-L641

i think need same check in settleChannel.

**Comment by loredanacirstea** [comment]
@nakajo2011 , thank you for observing this! 

We have implemented this change here: https://github.com/raiden-network/microraiden/pull/394.
While it is not required (see PR description), this check is good for clarity and helps to keep track of invariants.
