### ISSUE TITLE
Gas Cost Baseline

### ISSUE THREAD

**Issue by heikoheiko** [raiden-network/microraiden#4]
A: Sender
B: Receiver
C: Micropayment Channel Contract

### 1. Approve: 41
Base:21
Store Approval: 20 
### 2. Open: 36  (actual: 59)
Base:21
Transfer A>C: 5 + 5
Free Approval: -15
Store Channel: 20
### 3. Close: 26  (actual: 90)
Base:21
Transfer C>A: 5 + 5
Transfer C>B: 5 + 5
Free Channel: -15

## Custom: 77
Trusted Contract can deduct w/o approval.
Similar to approveAndCall (which would be 5 more expensive)
Saves one tx (21) and one sstore-srefund (5)
### 1. Open: 51
Base:21
Transfer A>C: 5 + 5
Store Channel: 20
### 2. Close: 26
Base:21
Transfer C>A: 5 + 5
Transfer C>B: 5 + 5
Free Channel: -15

**Comment by pcppcp** [comment]
closing as outdated
