### ISSUE TITLE
proxy endpoint returns invalid json

### ISSUE THREAD

**Issue by ellvtr** [raiden-network/microraiden#483]
My proxy endpoint returns a double quoted string, not valid json: `http://<hostname>:5000/api/1/channels/`
```
"[{\"blocks\": [3649488], \"sender_address\": \"0x08f2959A254e8d4fC389F7c9a658E0499223972d\"}, {\"blocks\": [3714905], \"sender_address\": \"0x6E2446aCfcec11CC4a60f36aFA061a9ba81aF7e0\"}, {\"blocks\": [3673933], \"sender_address\": \"0x3103a9f2Df697d068fbeCde6621b2CD783BB90B7\"}]"
```
While this endpoint returns valid json that can be parsed directly: `http://<hostname>:5000/api/1/stats`
Above "microraiden" instance is installed with pip in a venv.

I reported this issue internally yesterday and it may be fixed already. Just thought I'd like to have it on record that I reported an issue on an open source project :)

**Comment by pcppcp** [comment]
Thanks for reporting, fixed in #481 ;)
