### ISSUE TITLE
Urgent - Microraiden Demo Issue

### ISSUE THREAD

**Issue by rajjha** [raiden-network/microraiden#489]
"server won't accept this channel.
Please, close+settle+forget, and open a new channel"

this message is displayed on both chrome and firefox with metamask on the ropsten test network. it appears after depositing the TKN tokens and trying to sign them. Please suggest.

**Comment by andrevmatos** [comment]
That was caused by the Ropsten consensus issue between parity and geth:
https://github.com/paritytech/parity-ethereum/releases/tag/v2.0.8
We're fixing our deployed instances, everything should be running fine soon. Will keep the issue open until then

**Comment by rajjha** [comment]
Thanks Andre for your quick response. We have a planned demo with client on coming Monday(22nd ) and one of the candidate we have to demo is Micro-raiden. Waiting for your fix.

**Comment by andrevmatos** [comment]
Demos up and running on Ropsten again.

**Comment by rajjha** [comment]
Thanks Andre,
Do I need to do anything if I am running Microraiden on my local server?.
