### ISSUE TITLE
Allow for channel state recovery in WebUI

### ISSUE THREAD

**Issue by devium** [raiden-network/microraiden#71]
If the server is able to provide a larger balance proof after a failed payment, simply adopt that one.

This helps making client-side data recoverable/optional.

**Comment by devium** [comment]
> I plan to completely get rid of the client's state
We could also do that in the Python client. The only reason to keep current balances client-side after recoverability is to avoid asking the server for the current balance first. Not sure that's worth it, especially since we only need to do that once per session.

Basically the new protocol flow would be:
1. Client requests channel balance and resource pirce from server (including authentication).
2. Server sends most recent balance, signature, and price back to client.
3. Client validates balance signature ("oh yeah, right, I sent you that")
4. Client signs & sends old balance + price.
5. Server validates signature, sends content.

Authentication is another topic. I'd say just signing sequential nonces works fine. If the server rejects a nonce, also transmit the last signed nonce.

Ideas?

**Comment by pcppcp** [comment]
That's too complicated IMO. Client can simply bootstrap by asking for a list of open channels (`GET /api/1/channels/<client_addr>`) on start and select one of them - the response also includes most recent BP . I don't think mixing resource requests with channel status is necessary. 

(We can of course add some auth method to this api call if we want to protect client's privacy.)

**Comment by andrevmatos** [comment]
Auth can be made by signing something and sending to the server (before first request). It'd require one more click from user on first load (on sign), but only once (per session). It needs to be associated with the client somehow (e.g. the client's IP address), to avoid eternal access to client's balances by someone which manages to steal this signed data (MITM).

**Comment by andrevmatos** [comment]
The point with auth/signing some challenge is only for privacy, to not allow everyone to be able to query your current channel balance on a given service, but possibly leaking balance proof is not actually a concern, as it serve nothing but for the receiver to close the channel and receive the tokens.
Well, we use HTTPS everywhere, and I think we can assume that if it's broken, the whole privacy point is already lost. My proposal is:

The client becomes stateless. It should send something signed (at least e.g. balance 0 on first load). If not, it's considered a new client with no channel. It's over https, so this info won't be used by someone else to queue indefinitely for client's balance. The server, upon receiving some signed balance that is lower than current registered balance, set the same cookies (RDN-Open-Block, RDN-Sender-Balance, RDN-Balance-Signature) on the 402 request with the latest BP it have. The client, upon receiving a higher balance proof signed by self (and validating it), sets the new channel state and increment from there. If validation fails, it procceeds as if there was no channel.

Advantages of this method: cookies are persisted across sessions, so user's browser automatically is already loading last state; minimum effort: just need some checks on client, and some check+cookie set on server; compliant with current design. This would allow even multiple clients (with same account) to share a single channel, as if they get out of sync, the one behind, on next requisition, will get 402 again with newest BP.
