### ISSUE TITLE
Some questions about getBalanceMessage() and verifyBalanceProof()

### ISSUE THREAD

**Issue by LefterisJP** [raiden-network/microraiden#86]
I have a question for the micro-raiden architecture.

I noticed you have this function [`getBalanceMessage()`](https://github.com/loredanacirstea/raiden-micropayment-service/blob/8c84856ba153ea386988dfd313628afa044c6c75/contracts/contracts/RaidenMicroTransferChannels.sol#L115). This is the only place where [`addressToString()`](https://github.com/loredanacirstea/raiden-micropayment-service/blob/8c84856ba153ea386988dfd313628afa044c6c75/contracts/contracts/RaidenMicroTransferChannels.sol#L663) is [used](https://github.com/loredanacirstea/raiden-micropayment-service/blob/8c84856ba153ea386988dfd313628afa044c6c75/contracts/contracts/RaidenMicroTransferChannels.sol#L123).

Looking at `getBalanceMessage()` it seems like you can do without it. It just turns some fields to string and concatenates them. That can very easily be done on the client side and does not need a smart contract function.

Same goes for [`uintToString()`](https://github.com/loredanacirstea/raiden-micropayment-service/blob/8c84856ba153ea386988dfd313628afa044c6c75/contracts/contracts/RaidenMicroTransferChannels.sol#L628), apart from the fact that it's also [used in verifyBalanceProof()](https://github.com/loredanacirstea/raiden-micropayment-service/blob/8c84856ba153ea386988dfd313628afa044c6c75/contracts/contracts/RaidenMicroTransferChannels.sol#L159).

Looking further it seems you use `getBalanceMessage()` in `verifyBalanceProof()` and then use `verifyBalanceProof()` in the `close()` functions.

So here one thing to note. You should undo the `constant` keyword from both `getBalanceMessage()` and `verifyBalanceProof()` as you are not using them as constants. You call them from `close(). This is confusing to read.

Furthermore I don't see why you need to concatenate string, and have to do string manipulation which is expensive. Why not play with an array of bytes and encode/decode them?

**Comment by pcppcp** [comment]
@LefterisJP @loredanacirstea  are you happy with the reply? If yes, please close the issue :)
