### ISSUE TITLE
Document contract string concats vs. EIP712

### ISSUE THREAD

**Issue by loredanacirstea** [raiden-network/microraiden#88]
"Document the deficiency of lacking `personal_signTypedData` and state that the strings concatenation and string encoding will go away once https://github.com/ethereum/EIPs/pull/712 is done."

**Comment by andrevmatos** [comment]
To be implemented by #139

**Comment by loredanacirstea** [comment]
This can be closed, as it refers to documentation. docstrings updated in https://github.com/raiden-network/microraiden/pull/93 , mentioning EIP712 & temporary string concats.
