### ISSUE TITLE
Deploy & test on Ropsten

### ISSUE THREAD

**Issue by pcppcp** [raiden-network/microraiden#98]
We should switch to Ropsten eventually, to see how µRaiden behaves on a network with slower confirmation times.
The other reason is that Kovan isn't supported by geth.

**Comment by jannikluhn** [comment]
Once we switch we also have to increase the default number of confirmations as reorgs are more likely and deeper on Ropsten than to Kovan.

**Comment by pcppcp** [comment]
make n_confirmations parameter of the ChannelManager a configurable value

**Comment by loredanacirstea** [comment]
tested.
