### ISSUE TITLE
Contract versioning

### ISSUE THREAD

**Issue by pcppcp** [raiden-network/microraiden#99]
We should support contract versioning - if the contract is obsolete, it should i.e. have a method that returns new contract address.

(personally, I think it'd be better to just use contract address sent in http headers and have a 'obsolete' flag in the contract that'll abort all public methods if set)

**Comment by loredanacirstea** [comment]
Documenting contract versioning / upgradability scenarios.

1. Contract versioning 
  1.1. variable `string public version = ‘0.1’;`
  1.2. setter (ownerOnly) and getter for correct version - setting the new version is part of the deployment protocol.

Contract address is provided by uRadiden server/proxy.
Receiver has to close all his channels or incentivize clients to close them before upgrading uRaiden.
I don't think there is a need to lock contract functions.

- easy to implement
- Receiver unhappy, he might need to spend some money to close channels / incentivize clients; he cannot prevent clients from opening new channels while he waits for channels to be closed, so he has to put more work in his web UI to make the transition clear.
- contract remains usable, clients can use the contract directly and deposit tokens. Solution: they can close + wait for challenge period to end and settle the channel themselves. They just lose gas cost.

2. Try to recreate state in the new contract
Only open channels at that moment in time.
Clients can trigger state migration in the new contract from local data / events + old_contract.getChannelInfo() + the last balance proof + receiver's closing signature.
- a bit more complicated
- might be expensive

3. Use a library/contract + delegatecall and have the library address upgradable
- abi has to remain the same; signing / verifying balance proof interface might change, we might add support for delegates opening a channel etc.

**Comment by jannikluhn** [comment]
Another disadvantage of option 3: Requires trust in the owner as they could replace the library with a malicious one. Could probably be mitigated by a forced grace period for each update in which users could review the new library code and close all channels if necessary.
